### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Zerifore** [Praxxian/RPG-City-Generator#6]
This is an amazing website that I think will help out a lot of people! I have a request as to the spouse system to be implemented. I have noticed that all of the spouses are male-female couples. If you could add some sort of LGBT representation in this feature as well as maybe the gender feature that would be amazing!

**Comment by Praxxian** [comment]
I appreciate the feedback! There should be non-hetero couples already, but I will take a look at the frequency. It would also be easy to add in some more gender options. I'll do a little research into that. It's something I always meant to circle back to.

**Comment by Praxxian** [comment]
My new proposed new gender values: male, female, nonbinary, and genderfluid. Representation for the latter two are going to be much higher than those recorded in modern demographic surveys. This is not only for improved representation, but also because I think our modern data would be quite different in a world free of prejudice, institutional bias, etc.

My thoughts on Gender for the purposes of this tool is that it should be descriptive, i.e. it's really the gender expression. So when it says "male" that is what the players would be able to tell when meeting the character. Of course, DMs are free to create more detail, such as if they are trans or cis, for NPCs they want to feature prominently, or who become prominent from player actions.

Spouses: most male/female people will choose female/male, but "most" doesn't mean all. Once again, non-hetero couples will have more representation than IRL demographic data. Gender-fluid and nonbinary people have equal chance to choose any partner. Since partnering is not done in any particular order, this gives even greater odds that a man or woman would be paired with a nonbinary or genderfluid person.

If you feel like I have missed the mark here, let me know. Ultimately, I hope this will making DMing easier and more fun for everyone.

**Comment by Zerifore** [comment]
Both sound like amazing implements. I really appreciate the help and thought that you put into not only this instance but the whole project as well!

**Comment by Praxxian** [comment]
These updates are now live. Thanks again for your feedback!
